[package]
name = "lorepia-uniffi"
version.workspace = true
edition.workspace = true
publish.workspace = true
rust-version.workspace = true

[lib]
crate-type = ["cdylib", "staticlib", "rlib"]

[[bin]]
name = "uniffi-bindgen"
path = "src/bin/uniffi-bindgen.rs"

[dependencies]
lorepia-core = { path = "../../crates/core" }
thiserror.workspace = true
tokio.workspace = true
uniffi.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
